Update tests.yaml

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -1,7 +1,7 @@
 name: Tests
 
 on:
-  push:
+  pull_request:
     branches:
       - main
 jobs:
@@ -44,9 +44,24 @@ jobs:
       run: |
         mvn sonar:sonar -Dsonar.projectKey=FIAP-6SOAT-G10_fiap-fast-food-ms-cliente -Dsonar.organization=fiap-6soat-g10-1 -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=${{ secrets.SONAR_TOKEN }} -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml -P sonar-coverage
 
-  integration-tests:
+  coverage:
     runs-on: ubuntu-latest
     needs: unit-tests
+
+    steps:    
+      - name: Fetch Quality Gate Result
+        run: |
+          STATUS=$(curl -s -u $SONAR_TOKEN: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=FIAP-6SOAT-G10_fiap-fast-food-ms-cliente" | jq -r '.projectStatus.status')
+          if [ "$STATUS" != "OK" ]; then
+            echo "SonarQube Quality Gate failed."
+            exit 1
+          fi
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+
+  integration-tests:
+    runs-on: ubuntu-latest
+    needs: coverage
 
     steps:
     - name: Checkout code
